routes/web.php
<?php

use App\Http\Controllers\Admin\CarController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('homepage');
Route::get('detail/{car:slug}', [HomeController::class, 'detail'])->name('detail');
Route::get('contact', [HomeController::class, 'contact'])->name('contact');
Route::post('contact', [HomeController::class, 'contactStore'])->name('contact.store');

Route::group(['middleware' => 'is_admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
  Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
  Route::resource('cars', CarController::class);
  Route::put('cars/update-image/{id}', [CarController::class, 'updateImage'])->name('cars.updateImage');

  Route::get('messages', [MessageController::class, 'index'])->name('messages.index');
  Route::delete('messages/{message}', [MessageController::class, 'destroy'])->name('messages.destroy');
});

Auth::routes(['register' => false]);

resources/views/partials/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
      <a class="nav-link" href="{{ route('admin.dashboard.index') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

<li class="nav-item active">
    <a class="nav-link" href="{{ route('admin.cars.index') }}">
        <i class="fas fa-fw fa-car"></i>
        <span>Daftar Mobil</span>
    </a>
</li>
<li class="nav-item active">
    <a class="nav-link" href="{{ route('admin.messages.index') }}">
        <i class="fas fa-fw fa-envelope"></i>
        <span>Daftar Pesan</span>
    </a>
</li>
<li class="nav-item active">
    <a class="nav-link" onclick="document.getElementById('logout-form').submit()" href="#">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Logout</span>
        <form id="logout-form" action="{{ route('logout') }}" method="post">
        @csrf
        </form>
    </a>
</li>

</ul>